export const ADD_CONTRACT= "ADD_CONTRACT"
export const EDIT_CONTRACT= "EDIT_CONTRACT"
export const REMOVE_CONTRACT= "REMOVE_CONTRACT"
export const ADD_TO_FAVOURITE_CONTRACT= "ADD_TO_FAVOURITE_CONTRACT"
export const REMOVE_FAVOURITE_CONTRACT= "REMOVE_FAVOURITE_CONTRACT"

